"""username is now fixed

Revision ID: 161d27d0ed46
Revises: fbe7cb6c4c37
Create Date: 2021-02-24 13:52:05.014119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161d27d0ed46'
down_revision = 'fbe7cb6c4c37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
