"""fixed imagesassfsa

Revision ID: 2491c5a09a8c
Revises: 9d83c57eed69
Create Date: 2021-03-08 16:27:06.003359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2491c5a09a8c'
down_revision = '9d83c57eed69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
