"""added images

Revision ID: 2dd9fde8b50a
Revises: 491f0c556dda
Create Date: 2021-03-08 15:07:54.487198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd9fde8b50a'
down_revision = '491f0c556dda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simplehub', sa.Column('generated_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simplehub', 'generated_url')
    # ### end Alembic commands ###
