"""add detailedhub_image

Revision ID: 3e5b315da4b1
Revises: 803f7a0fe86b
Create Date: 2021-03-08 16:32:53.045126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e5b315da4b1'
down_revision = '803f7a0fe86b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detailedhub_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detailedhub_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['detailedhub_id'], ['detailedhub.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('detailedhub_id'),
    sa.UniqueConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detailedhub_image')
    # ### end Alembic commands ###
