"""added images

Revision ID: 491f0c556dda
Revises: 3bb6c5c33d4e
Create Date: 2021-03-08 14:53:01.674716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491f0c556dda'
down_revision = '3bb6c5c33d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detailedhub', sa.Column('generated_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detailedhub', 'generated_url')
    # ### end Alembic commands ###
