"""fixed imagesas

Revision ID: 62576f3e82e8
Revises: c7e36fbb5d6f
Create Date: 2021-03-08 15:38:44.588778

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '62576f3e82e8'
down_revision = 'c7e36fbb5d6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.add_column('user_detailedhub', sa.Column('detailedhub_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_detailedhub_detailed_hub_id_fkey', 'user_detailedhub', type_='foreignkey')
    op.create_foreign_key(None, 'user_detailedhub', 'detailedhub', ['detailedhub_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_detailedhub', 'detailed_hub_id')
    op.add_column('user_simplehub', sa.Column('simplehub_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_simplehub_simple_hub_id_fkey', 'user_simplehub', type_='foreignkey')
    op.create_foreign_key(None, 'user_simplehub', 'simplehub', ['simplehub_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_simplehub', 'simple_hub_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_simplehub', sa.Column('simple_hub_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_simplehub', type_='foreignkey')
    op.create_foreign_key('user_simplehub_simple_hub_id_fkey', 'user_simplehub', 'simplehub', ['simple_hub_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_simplehub', 'simplehub_id')
    op.add_column('user_detailedhub', sa.Column('detailed_hub_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_detailedhub', type_='foreignkey')
    op.create_foreign_key('user_detailedhub_detailed_hub_id_fkey', 'user_detailedhub', 'detailedhub', ['detailed_hub_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_detailedhub', 'detailedhub_id')
    op.create_table('image',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_encoding', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'image_id', 'image_key', name='image_pkey')
    )
    # ### end Alembic commands ###
