"""username is now fixed

Revision ID: 62a63f98d280
Revises: 161d27d0ed46
Create Date: 2021-02-24 13:52:40.286075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62a63f98d280'
down_revision = '161d27d0ed46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
