"""username is now nullable

Revision ID: 6857f26c33bd
Revises: 709680a9f13d
Create Date: 2021-02-24 13:45:44.153312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6857f26c33bd'
down_revision = '709680a9f13d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
