"""Removed from User

Revision ID: 69916cffae82
Revises: ac099c18719e
Create Date: 2021-02-24 13:30:35.102551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69916cffae82'
down_revision = 'ac099c18719e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_contact_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'contact_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_contact_id_fkey', 'user', 'contact', ['contact_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
