"""Added User Fields

Revision ID: 860a5335ebbd
Revises: eb61c7f6b223
Create Date: 2021-02-24 12:46:34.063049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860a5335ebbd'
down_revision = 'eb61c7f6b223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(), nullable=False))
    op.add_column('user', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
