"""fixed imagesassfsa

Revision ID: 961d70f86810
Revises: 62576f3e82e8
Create Date: 2021-03-08 15:59:01.642537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '961d70f86810'
down_revision = '62576f3e82e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'image_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
