"""fixed imagesassfsa

Revision ID: 9d83c57eed69
Revises: 961d70f86810
Create Date: 2021-03-08 16:07:33.507622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d83c57eed69'
down_revision = '961d70f86810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
