"""Added Desription to simplehubs

Revision ID: ac099c18719e
Revises: 860a5335ebbd
Create Date: 2021-02-24 13:20:39.911120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac099c18719e'
down_revision = '860a5335ebbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SimpleHub', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SimpleHub', 'description')
    # ### end Alembic commands ###
