"""username is now fixed

Revision ID: f6c4d9bbb6be
Revises: 62a63f98d280
Create Date: 2021-02-24 13:53:37.349923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6c4d9bbb6be'
down_revision = '62a63f98d280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
