"""username is now fixed

Revision ID: faa29fc5ccc3
Revises: f6c4d9bbb6be
Create Date: 2021-02-24 13:54:33.051568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa29fc5ccc3'
down_revision = 'f6c4d9bbb6be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
