"""username is now nullable

Revision ID: fbe7cb6c4c37
Revises: 6857f26c33bd
Create Date: 2021-02-24 13:47:52.593991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe7cb6c4c37'
down_revision = '6857f26c33bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
